### ISSUE TITLE
"-continue" parameter breaks result page (claims success)

### ISSUE THREAD

**Issue by lemmy** [alygin/vscode-tlaplus#143] opened 2020-01-31 23:24 UTC
![Peek 2020-01-31 15-20](https://user-images.githubusercontent.com/88777/73581296-8bf4ee00-443d-11ea-921c-8276f1b253b8.gif)

Spec/Model from this commit https://github.com/lemmy/BlockingQueue/commit/774ec57054c2e1a56a6eb5c1e2506548d2158dd7
Requires most recent TLC because of https://github.com/tlaplus/tlaplus/commit/d5b5a7fa9f5ccdb78edbe2b286ca08ea9b42dc73

**Comment by alygin** [comment] 2020-02-01 07:13
@lemmy, could you, please, send me your resulting .out-file? I can't reproduce the problem when running in the desktop version of VSCode, but I have no warnings generated, just lots of "Invariant Invariant is violated" errors and corresponding error traces. They are displayed correctly.

I can also see a change marker (on the scrollbar) at your screencast, it looks like you made some modification in the spec. What is that modification? Is it crucial for reproducing the problem?

**Comment by alygin** [comment] 2020-02-01 09:14
I've reproduced it, thanks, no more need for the .out-file.

**Comment by alygin** [comment] 2020-02-01 10:37
The fix is available in the latest pre-release.

**Comment by alygin** [comment] 2020-02-01 15:47
For further improvement: #146

**Comment by alygin** [comment] 2020-02-03 07:09
Released in v1.4.

**Closed by alygin** 2020-02-03 07:09 UTC
Labels: bug
