### ISSUE TITLE
Blocker: TLA+ model checking (web) view not populated when model-checking again

### ISSUE THREAD

**Issue by lemmy** [alygin/vscode-tlaplus#167] opened 2020-08-26 19:20 UTC
On Windows (and Linux) with VSCode *newer* than `1.46.1` and any version of this extension in `1.5.0..1.5.1-alpha-2`, re-running model-checking results in an empty web view (iff the web view gets closed in between).  The Windows task manager confirms that TLC spawns and terminates correctly.

![2020-08-26_12-12-17](https://user-images.githubusercontent.com/88777/91346575-e8cb4380-e795-11ea-826b-f61b5f747170.gif)

(Downgrading to VSCode 1.46.1 reliably fixes the issue)

**Comment by lemmy** [comment] 2020-09-03 21:28
@alygin Any way we can help with this issue?

**Comment by lemmy** [comment] 2020-09-12 04:50
I took a stab at this tonight and I [agree with the VSCode authors](https://code.visualstudio.com/api/extension-guides/webview#should-i-use-a-webview) that webviews are a clutch.  The issue is gone when, instead of [caching the webview](https://github.com/alygin/vscode-tlaplus/blob/00f260baf68b96fd2114a706b8e85f5c3369f42b/src/checkResultView.ts#L7-L9), a new one is always created.  There are a [few](https://github.com/microsoft/vscode/issues/102044) [issues](https://github.com/microsoft/vscode/issues/102102) related to webviews that popped up after the 1.47 release, but they don't fit.  Perhaps, the root cause if tightened security related to the `[resourcePath](https://github.com/alygin/vscode-tlaplus/blob/00f260baf68b96fd2114a706b8e85f5c3369f42b/src/checkResultView.ts#L108-L112)` that somehow becomes invalid.

**Comment by alygin** [comment] 2020-09-15 23:22
@lemmy, you're absolutely right. The problem is caused by resource paths invalidation after web view closing, and dropping the page source cache solves the issue.

Regarding the radical idea, I thought about possible ways to abstain from using a web view when I just started working on the extension, but I failed to come up with a good UI that would be only based on the text editor features. But VS Code has been rapidly evolving since then, so I guess, some interesting ideas might be implemented now. Though, despite my love of text-based UIs, I honestly don't see how the web view could be completely replaced here without losing usability.

**Comment by alygin** [comment] 2020-09-15 23:36
@lemmy, here's a pre-release with the issue solved: [v1.5.1-beta.1](https://github.com/alygin/vscode-tlaplus/releases/tag/v1.5.1-beta.1)

**Comment by alygin** [comment] 2020-09-16 04:38
BTW, WebView is finding its way to other parts of VS Code: [46585](https://github.com/microsoft/vscode/issues/46585). I hope it'll become more robust as it becomes more widely used.

**Comment by alygin** [comment] 2020-09-16 05:59
Fixed in v1.5.1. Please, reopen the issue if the problem still remains in your environment.

**Closed by alygin** 2020-09-16 05:59 UTC
Labels: bug
