### ISSUE TITLE
How to disable coverage?

### ISSUE THREAD

**Issue by lemmy** [alygin/vscode-tlaplus#172] opened 2020-10-07 00:50 UTC
A user cannot disable TLC's coverage collection, even though collecting coverage data has significant overhead for large-scale model-checking.  

https://github.com/alygin/vscode-tlaplus/blob/50bad5f5b0405570435f3c4b107ad2da79fe3a0d/src/tla2tools.ts#L181

My suggestion would be to *not* set `-coverage` at all.

**Comment by lemmy** [comment] 2020-10-07 17:04
Yes:

![Screenshot from 2020-10-07 10-03-50](https://user-images.githubusercontent.com/88777/95363595-87ae8980-0884-11eb-8a5f-3a49744be359.png)

**Comment by lemmy** [comment] 2021-01-03 16:55
Also, one of the messages codes related to coverage is not handled by the extension: `Unexpected message code: 2778`

**Comment by alygin** [comment] 2021-01-04 09:36
> Also, one of the messages codes related to coverage is not handled by the extension: `Unexpected message code: 2778`

@lemmy , thanks, I've created an issue for this problem: #186

**Comment by klinvill** [comment] 2021-03-25 00:18
I agree that it seems reasonable to enable coverage by default. Ideally, there would be a -coverage argument that could passed to disable coverage (which could then be specified by the user in the extension's settings). However, as alluded to above, it looks like the only way to currently do that is by not passing a -coverage argument at all to TLC. This is because TLC runs coverage collection if the coverage argument is >= 0 ([see here](https://github.com/tlaplus/tlaplus/blob/d5654d93bc5787026382201fda7aa3fbb55222c6/tlatools/org.lamport.tlatools/src/tlc2/TLCGlobals.java#L103)), and it also ensures that a negative value is never be passed as the coverage argument ([see here](https://github.com/tlaplus/tlaplus/blob/38841e3fede3590f2c4b03be56db735dd7b7f818/tlatools/org.lamport.tlatools/src/tlc2/TLC.java#L547)).

@lemmy would you be open to a PR allowing a coverage argument of -1 that would explicitly disable coverage? That should also knock out this issue. If so, I'll take a look into it.

**Comment by lemmy** [comment] 2021-03-25 03:41
@klinvill Let's not make TLC more complex. :-)

Generally, TLC's command-line parameters are misplaced in the extension settings.  For example, I repeatedly forget that I added `-simulate` in the settings and then am puzzled about TLC's behavior.  Instead, why don't we show TLC's parameters in the command palette after the user hits 'Check model with TLC'?  What is pre-populated in the palette would come from the extension's settings (or is set to the previous user input).  More importantly, though, a user can easily modify it and e.g., remove `-coverage 1`.

**Comment by lemmy** [comment] 2021-03-26 18:24
FWIW: Evaluating trace expression is a use case where users don't want coverage information.  Likewise, I'm usually not interested in coverage when I debug a spec.

**Comment by klinvill** [comment] 2021-03-26 19:20
@lemmy is something like this what you were thinking of? I was originally worried about the friction of introducing an extra keystroke every time you want to check a model, but I'm not minding it as much as I thought I would.
 
https://user-images.githubusercontent.com/6043161/112682061-cf25d380-8e2c-11eb-8478-f78204069102.mp4

**Comment by lemmy** [comment] 2021-03-26 19:39
Terrific, this is exactly what I meant! :-) Where can I pull it to get a feel for it?

**Comment by klinvill** [comment] 2021-03-26 19:51
It's still unpolished right now, but I setup a branch here: https://github.com/klinvill/vscode-tlaplus/tree/klinvill/tlc-options-prompt. Definitely let me know what you think.

**Comment by lemmy** [comment] 2021-03-26 20:48
https://github.com/lemmy/vscode-tlaplus/commit/9350020b9f9f493465998bca113972f776810f92

**Comment by alygin** [comment] 2021-04-16 20:14
Pre-released in [1.5.5-beta.1](https://github.com/alygin/vscode-tlaplus/releases/tag/v1.5.5-beta.1)

**Comment by klinvill** [comment] 2021-08-14 01:43
We can close this since coverage can be disabled by simply removing the coverage argument from the options prompt introduced in #207. I just re-confirmed that it works in [1.6.0-alpha.2](https://github.com/alygin/vscode-tlaplus/releases/tag/v1.6.0-alpha.2)

**Closed** 2021-11-03 20:46 UTC
