### ISSUE TITLE
Model Checking Pane empty in VSCode online because of unsafe-inline

### ISSUE THREAD

**Issue by lemmy** [alygin/vscode-tlaplus#139] opened 2020-01-13 19:09 UTC
![Peek 2020-01-13 11-08](https://user-images.githubusercontent.com/88777/72284140-1e4f6200-35f5-11ea-86a7-b6efdac7a3e8.gif)

```
main.js:441 Refused to load the stylesheet 'https://4651e61d-b770-415f-8cbc-cbbc176dae2d.vscode-webview-test.com/26076a4de974ead31f97692a0d32f90d735645c0/vscode-resource/file///home/vsonline/.vscode-remote/extensions/alygin.vscode-tlaplus-1.3.1/resources/check-result-view.css' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' https://*.vscode-webview-test.com/26076a4de974ead31f97692a0d32f90d735645c0". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

(anonymous) @ main.js:441
setTimeout (async)
(anonymous) @ main.js:438


main.js:441 Refused to load the script 'https://4651e61d-b770-415f-8cbc-cbbc176dae2d.vscode-webview-test.com/26076a4de974ead31f97692a0d32f90d735645c0/vscode-resource/file///home/vsonline/.vscode-remote/extensions/alygin.vscode-tlaplus-1.3.1/resources/check-result-view.js' because it violates the following Content Security Policy directive: "script-src https://*.vscode-webview-test.com/26076a4de974ead31f97692a0d32f90d735645c0". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

(anonymous) @ main.js:441
setTimeout (async)
(anonymous) @ main.js:438
```

Something appears to have changed in VSCode online, because version 1.1 and 1.2 - which I remember to work correctly - show the same error.

**Comment by alygin** [comment] 2020-01-13 22:34
You're right, the `usafe-inline` is the root cause here. I'll have a look at it.

**Comment by alygin** [comment] 2020-01-13 23:48
@lemmy, could you, please, try this build?
[vscode-tlaplus-1.3.2.vsix.zip](https://github.com/alygin/vscode-tlaplus/files/4056581/vscode-tlaplus-1.3.2.vsix.zip)

**Comment by lemmy** [comment] 2020-01-13 23:58
Awesome, it work!

**Comment by alygin** [comment] 2020-01-14 00:18
v1.3.2 with this fix has been published. Thanks for helping with this one.

**Closed** 2020-01-14 01:12 UTC
Labels: bug
